Update README.md
rathena/vsce-rathena-language-support pull request #2
Opened 2023-05-12 12:21 UTC by secretdataz

2023-05-15 11:30 UTC, Akkarinage requested changes

2023-05-15 11:30 UTC, Akkarinage commented on README.md
> +Files that start with `//===== rAthena Script` or `//!rathena` will also be automatically detected as an rAthena script.
```suggestion
rAthena Language Support automatically highlights files with .rascript extension.

Files that start with `//===== rAthena Script` or `//!rathena` will also be automatically detected as an rAthena script.
```

Markdown requires an empty newline to display as "hard return".

2023-05-15 13:52 UTC, aleos89 approved these changes

2023-05-19 21:14 UTC, Akkarinage approved these changes

2023-05-19 21:15 UTC, merged